module.exports = {
  siteUrl: process.env.NEXT_PUBLIC_SITE_URL || 'https://fabric-shop-frontend-production.up.railway.app',
  generateRobotsTxt: true,
  sitemapSize: 7000,
  exclude: [
    '/api/*',
    '/_next/*',
    '/admin/*',
    '/404',
    '/500',
    '/not-found',
    '/error',
    '/email-verify/*',
    '/forget-password/*',
    '/order/*',
    '/product-details/*',
    '/blog-details/*',
    '/blog-details-2/*',
    '/checkout',
    '/shop-right-sidebar',
    '/shop-hidden-sidebar',
    '/shop-category',
    '/product-details-video',
    '/product-details-countdown',
    '/product-details-swatches',
    '/blog-grid',
    '/blog-list',
    '/blog-details',
    '/blog-details-2',
    '/compare',
    '/coupon',
    '/forgot',
    '/register',
    '/profile',
    '/search',
    '/home-3',
    '/home-4'
  ],
  robotsTxtOptions: {
    policies: [
      { userAgent: '*', allow: '/' },
      { userAgent: '*', disallow: ['/api/*', '/admin/*', '/_next/*', '/checkout'] },
    ],
    additionalSitemaps: [
      (process.env.NEXT_PUBLIC_SITE_URL || 'https://fabric-shop-frontend-production.up.railway.app') + '/sitemap.xml',
    ],
  },
}; 