import './globals.scss';
import { Jost } from 'next/font/google';
import Providers from '../components/provider';
import GoogleAnalytics from '../components/analytics/GoogleAnalytics';
import MicrosoftClarity from '../components/analytics/MicrosoftClarity';

export const metadata = {
  title: 'Shofy - e-Commerce Next js Template',
  description: 'Generated by create next app',
};

const jost = Jost({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--tp-ff-body",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={jost.variable}>
      <head>
        <GoogleAnalytics />
        <MicrosoftClarity />
      </head>
      <body className={jost.className}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}